services:
  rest-api:
    container_name: rest-api
    image: vakadev/daily-rest-api:latest
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: vaka_daily_db
      DB_USERNAME: postgres
      DB_PASSWORD: 12345

      REST_API_PORT: 8080
      REST_API_NOTIFICATION_LOOP: 10

      TG_BOT_HOST: tg-bot
      TG_BOT_PORT: 8889
      TG_BOT_ENABLED: true

    # Проброс порта можно убрать, чтобы запретить использование REST API вне localhost
    ports:
      - "${REST_API_PORT}:8080"
    depends_on:
      - db


  mvc:
    container_name: mvc
    image: vakadev/daily-mvc:latest
    environment:
      REST_API_HOST: rest-api
      REST_API_PORT: 8080

      MVC_PORT: 8081
    ports:
      - "${MVC_PORT}:8081"
    depends_on:
      - rest-api

  tg-bot:
    container_name: tg-bot
    image: vakadev/daily-tg-bot:latest
    environment:
      REST_API_HOST: rest-api
      REST_API_PORT: 8080
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      TG_BOT_ENABLED: true
      TG_BOT_PORT: 8889
    ports:
      - "${TG_BOT_PORT}:8888"
    depends_on:
      - rest-api


  db:
    container_name: db
    image: vakadev/daily-db:latest
    restart: always
    environment:
      POSTGRES_DB: vaka_daily_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: