services:
  rest-api:
    container_name: rest-api
    build:
      context: ../rest-api
    image: vakadev/daily-rest-api:latest
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: vaka_daily_db
      DB_USERNAME: postgres
      DB_PASSWORD: 12345

      NOTIFICATION_ENABLED: true
      TG_BINDING_ENABLED: true

      REST_API_PORT: 8080

      TG_BOT_HOST: tg-bot
      TG_BOT_PORT: 8889
      TG_BOT_ENABLED: true

    # Проброс порта можно убрать, чтобы запретить использование REST API вне localhost
    ports:
      - "${REST_API_PORT}:8080"
    depends_on:
      - db

  notifier:
    container_name: notifier
    build:
      context: ../notifier
    image: vakadev/daily-notifier:latest
    environment:
      REST_API_HOST: rest-api
      REST_API_PORT: 8080

      KAFKA_BOOTSTRAP_HOST: broker
      NOTIFIER_PORT: 8090
    ports:
      - "${NOTIFIER_PORT}:8090"
    depends_on:
      - rest-api
    
#  mvc:
#    container_name: mvc
#    build: mvc
#    image: vakadev/daily-mvc:latest
#    environment:
#      REST_API_HOST: rest-api
#      REST_API_PORT: 8080
#
#      MVC_PORT: 8081
#    ports:
#      - "${MVC_PORT}:8081"
#    depends_on:
#      - rest-api
#
#  tg-bot:
#    container_name: tg-bot
#    build: tg-bot
#    image: vakadev/daily-tg-bot:latest
#    environment:
#      REST_API_HOST: rest-api
#      REST_API_PORT: 8080
#
#      TG_BOT_ENABLED: true
#      TG_BOT_PORT: 8889
#    ports:
#      - "${TG_BOT_PORT}:8888"
#    depends_on:
#      - rest-api
    

  db:
    container_name: db
    build: db
    image: vakadev/daily-db:latest
    restart: always
    environment:
      POSTGRES_DB: vaka_daily_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:29092,PLAINTEXT_C://0.0.0.0:9093,PLAINTEXT_L://0.0.0.0:9092,
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://broker:29092,PLAINTEXT_L://localhost:9092,PLAINTEXT_C://broker:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_L:PLAINTEXT,PLAINTEXT_C:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      - broker
    ports:
      - "7777:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=broker
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker:9093
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
  
volumes:
  postgres_data: